# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45fc0405d338c61f40bf182881fa4d6b95446525926ae2bd040d79c959a50595fd7076288c14c6a8caf4942002f75a02f566e17a0fb4922ff06ced73745adfc8

test:
  secret_key_base: 2aad659a8e3fa6df8c63d5a6d891893c1b5c867a9b24a72da9cff63f63852f915ee43b954373d79c09e7df589c62641e029833e65b705adaa75c3c309875db8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
